import { CorrectSentence } from "./quizModel"

// const xAxisWords: XAxisWords = [
//     "eat",
//     "drink",
//     "sleep",
//     "run",
//     "walk",
//     "study",
//     "use",
//     "watch",
//     "listen",
//     "buy",
//   ];
//   const yAxisWords: YAxisWords = ["I", "He", "She", "You", "They", "We"];

export type SentenceManager = {
    [key:string]:CorrectSentence
}

const sentenceManager:SentenceManager = {
    "Ieat":{words:["I", "eat", "rice", "everyday"], type:"correct", translation:"私は毎日ライスを食べる"},
    "Idrink":{words:["I", "drink", "tea", "everyday"], type:"correct", translation:"私は毎日お茶を飲む"},
    "Isleep":{words:["I", "sleep", "at", "10:00", "pm"], type:"correct", translation:"私は午後10時に寝る"},
    "Irun":{words:["I", "run", "at", "the", "ground"], type:"correct", translation:"私はグラウンドで走る"},
    "Iwalk":{words:["I", "walk", "to", "school"], type:"correct", translation:"私は歩いて学校に行く"},
    "Istudy":{words:["I", "study", "English", "everyday"], type:"correct", translation:"私は毎日英語を勉強している"},
    "Iuse":{words:["I", "use", "a", "pencil", "at", "school"], type:"correct", translation:"私は学校で鉛筆を使う"},
    "Iwatch":{words:["I", "watch", "Youtube", "at", "home"], type:"correct", translation:"私は家でYoutubeを見る"},
    "Ilisten":{words:["I", "listen", "to", "music", "everyday"], type:"correct", translation:"私は毎日音楽を聴いている"},
    "Ibuy":{words:["I", "buy", "snacks", "at", "the", "store"], type:"correct", translation:"私はお店でおやつを買う"},
    "Heeat":{words:["He", "eats", "rice", "everyday"], type:"correct", translation:"彼は毎日ライスを食べる"},
    "Hedrink":{words:["He", "drinks", "tea", "everyday"], type:"correct", translation:"彼は毎日お茶を飲む"},
    "Hesleep":{words:["He", "sleeps", "at", "10:00", "pm"], type:"correct", translation:"彼は午後10時に寝る"},
    "Herun":{words:["He", "runs", "at", "the", "ground"], type:"correct", translation:"彼はグラウンドで走る"},
    "Hewalk":{words:["He", "walks", "to", "school"], type:"correct", translation:"彼は歩いて学校に行く"},
    "Hestudy":{words:["He", "studies", "English", "everyday"], type:"correct", translation:"彼は毎日英語を勉強している"},
    "Heuse":{words:["He", "uses", "a", "pencil", "at", "school"], type:"correct", translation:"彼は学校で鉛筆を使う"},
    "Hewatch":{words:["He", "watches", "Youtube", "at", "home"], type:"correct", translation:"彼は家でYoutubeを見る"},
    "Helisten":{words:["He", "listens", "to", "music", "everyday"], type:"correct", translation:"彼は毎日音楽を聴いている"},
    "Hebuy":{words:["He", "buys", "snacks", "at", "the", "store"], type:"correct", translation:"彼はお店でおやつを買う"},
    "Sheeat":{words:["She", "eats", "rice", "everyday"], type:"correct", translation:"彼女は毎日ライスを食べる"},
    "Shedrink":{words:["She", "drinks", "tea", "everyday"], type:"correct", translation:"彼女は毎日お茶を飲む"},
    "Shesleep":{words:["She", "sleeps", "at", "10:00", "pm"], type:"correct", translation:"彼女は午後10時に寝る"},
    "Sherun":{words:["She", "runs", "at", "the", "ground"], type:"correct", translation:"彼女はグラウンドで走る"},
    "Shewalk":{words:["She", "walks", "to", "school"], type:"correct", translation:"彼女は歩いて学校に行く"},
    "Shestudy":{words:["She", "studies", "English", "everyday"], type:"correct", translation:"彼女は毎日英語を勉強している"},
    "Sheuse":{words:["She", "uses", "a", "pencil", "at", "school"], type:"correct", translation:"彼女は学校で鉛筆を使う"},
    "Shewatch":{words:["She", "watches", "Youtube", "at", "home"], type:"correct", translation:"彼女は家でYoutubeを見る"},
    "Shelisten":{words:["She", "listens", "to", "music", "everyday"], type:"correct", translation:"彼女は毎日音楽を聴いている"},
    "Shebuy":{words:["She", "buys", "snacks", "at", "the", "store"], type:"correct", translation:"彼女はお店でおやつを買う"},
    "Youeat":{words:["You", "eat", "rice", "everyday"], type:"correct", translation:"あなたは毎日ライスを食べる"},
    "Youdrink":{words:["You", "drink", "tea", "everyday"], type:"correct", translation:"あなたは毎日お茶を飲む"},
    "Yousleep":{words:["You", "sleep", "at", "10:00", "pm"], type:"correct", translation:"あなたは午後10時に寝る"},
    "Yourun":{words:["You", "run", "at", "the", "ground"], type:"correct", translation:"あなたはグラウンドで走る"},
    "Youwalk":{words:["You", "walk", "to", "school"], type:"correct", translation:"あなたは歩いて学校に行く"},
    "Youstudy":{words:["You", "study", "English", "everyday"], type:"correct", translation:"あなたは毎日英語を勉強している"},
    "Youuse":{words:["You", "use", "a", "pencil", "at", "school"], type:"correct", translation:"あなたは学校で鉛筆を使う"},
    "Youwatch":{words:["You", "watch", "Youtube", "at", "home"], type:"correct", translation:"あなたは家でYoutubeを見る"},
    "Youlisten":{words:["You", "listen", "to", "music", "everyday"], type:"correct", translation:"あなたは毎日音楽を聴いている"},
    "Youbuy":{words:["You", "buy", "snacks", "at", "the", "store"], type:"correct", translation:"あなたはお店でおやつを買う"},
    "Theyeat":{words:["They", "eat", "rice", "everyday"], type:"correct", translation:"彼らは毎日ライスを食べる"},
    "Theydrink":{words:["They", "drink", "tea", "everyday"], type:"correct", translation:"彼らは毎日お茶を飲む"},
    "Theysleep":{words:["They", "sleep", "at", "10:00", "pm"], type:"correct", translation:"彼らは午後10時に寝る"},
    "Theyrun":{words:["They", "run", "at", "the", "ground"], type:"correct", translation:"彼らはグラウンドで走る"},
    "Theywalk":{words:["They", "walk", "to", "school"], type:"correct", translation:"彼らは歩いて学校に行く"},
    "Theystudy":{words:["They", "study", "English", "everyday"], type:"correct", translation:"彼らは毎日英語を勉強している"},
    "Theyuse":{words:["They", "use", "a", "pencil", "at", "school"], type:"correct", translation:"彼らは学校で鉛筆を使う"},
    "Theywatch":{words:["They", "watch", "Youtube", "at", "home"], type:"correct", translation:"彼らは家でTheytubeを見る"},
    "Theylisten":{words:["They", "listen", "to", "music", "everyday"], type:"correct", translation:"彼らは毎日音楽を聴いている"},
    "Theybuy":{words:["They", "buy", "snacks", "at", "the", "store"], type:"correct", translation:"彼らはお店でおやつを買う"},
    "Weeat":{words:["We", "eat", "rice", "everyday"], type:"correct", translation:"私たちは毎日ライスを食べる"},
    "Wedrink":{words:["We", "drink", "tea", "everyday"], type:"correct", translation:"私たちは毎日お茶を飲む"},
    "Wesleep":{words:["We", "sleep", "at", "10:00", "pm"], type:"correct", translation:"私たちは午後10時に寝る"},
    "Werun":{words:["We", "run", "at", "the", "ground"], type:"correct", translation:"私たちはグラウンドで走る"},
    "Wewalk":{words:["We", "walk", "to", "school"], type:"correct", translation:"私たちは歩いて学校に行く"},
    "Westudy":{words:["We", "study", "English", "everyday"], type:"correct", translation:"私たちは毎日英語を勉強している"},
    "Weuse":{words:["We", "use", "a", "pencil", "at", "school"], type:"correct", translation:"私たちは学校で鉛筆を使う"},
    "Wewatch":{words:["We", "watch", "Youtube", "at", "home"], type:"correct", translation:"私たちは家でWetubeを見る"},
    "Welisten":{words:["We", "listen", "to", "music", "everyday"], type:"correct", translation:"私たちは毎日音楽を聴いている"},
    "Webuy":{words:["We", "buy", "snacks", "at", "the", "store"], type:"correct", translation:"私たちはお店でおやつを買う"},
}

export default sentenceManager